# Generated by Django 4.2.13 on 2024-07-05 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlikemodel',
            options={'ordering': ['created_at'], 'verbose_name': 'Post Like', 'verbose_name_plural': 'Posts Likes'},
        ),
    ]
